### ISSUE TITLE
Model as env variable

### ISSUE THREAD

**Issue by Netzvamp** [pavelzbornik/whisperX-FastAPI#1]
Hey, i was just looking for an whisperx fastapi implementation and found your fresh project just 4 hours after your first commit 😄 

Could you set the default model as an env variable, so i don't have to replace the line in my Dockerfile? 

Thanks 👍

**Comment by pavelzbornik** [comment]
Hey, 

it is still early version, so happy for any feedback.

It is quite simple to do it the same way as for HF token. Will look at it after holidays (traveling at this moment)
