### ISSUE TITLE
ffmpeg video to audio conversion parameters hardcoded?

### ISSUE THREAD

**Issue by IIe4enka** [pavelzbornik/whisperX-FastAPI#28]
Amazing repo, thanks for your contribution! 

I'm trying to optimzie my pipeline so it doesnt squish or break the sound channel, but it seems that in your video to audio method you hardcoded 16000 rate and didnt set any bit rate. 

I.e. I wanted to try:
    temp_filename = NamedTemporaryFile(delete=False).name
    subprocess.call(
        [
            "ffmpeg",
            "-y",  # Overwrite output file if it exists"
            "-i",
            file,
            "-vn",
            "-ac",
            "1",  # Mono audio
            "-ar", "44100",  
            "-b:a", "192k",  
            "-f",
            "wav",  # Output format WAV
            temp_filename,
        ]
    )
    return temp_filename

Is there a reason why rate was clipped to 16000 and no bit rate was set?

**Comment by pavelzbornik** [comment]
Actually didn't put much thought into the process :) ,found some solution which worked.... 

Will make the change with the option to define it in the API parameters.

Thanks for spotting!

**Comment by pavelzbornik** [comment]
Now I realised the sample rate value, I took it as it was defined in WhisperX, which to my understanding all incoming audio is resampled to 16k, you can check at https://github.com/m-bain/whisperX/blob/main/whisperx/audio.py

My reading is regardless of the audio quality parameters of video-to-audio conversion WhisperX will resample it anyway to lower quality.

**Comment by IIe4enka** [comment]
Thanks for the info, the audio indeed seems to be resampled automatically, quite unfortunate. 
Any ideas on what video \ audio preprocessing could improve quality of transcribtion? 
I've been looking into separating channels as separate transcribtions for better diarization and playing with audio filters, but maybe you've got some ideas? Would love to hear if anything <3

**Comment by pavelzbornik** [comment]
honestly don't know, actually never had an issue with the quality of the transcription except for hallucinations, for whisper-based transcription models they resample the audio to 16k mono, you can see it also in OpenAI whisper audio process https://github.com/openai/whisper/blob/e90b8fa7e845ae184ed9aa0babcf3cde6f16719e/whisper/audio.py
