### ISSUE TITLE
Incorrect task value passing to process_audio_task task argument.

### ISSUE THREAD

**Issue by gahoo** [pavelzbornik/whisperX-FastAPI#46]
https://github.com/pavelzbornik/whisperX-FastAPI/blob/d2df3dc0ef2675340f70ae379b9fddc0529cea8c/app/services.py#L126

`process_audio_task` task argument accepts `str`, meanwhile model_params.task is a `TaskEnum`. Use `model_params.task.value` instead should fix this issue.

**Comment by gahoo** [comment]
https://github.com/pavelzbornik/whisperX-FastAPI/blob/d2df3dc0ef2675340f70ae379b9fddc0529cea8c/app/whisperx_services.py#L266

Here has the same issue.

**Comment by pavelzbornik** [comment]
Thanks for the fix, the PR is merged
