### ISSUE TITLE
Po zpracovani tasku to po sobe neuklidi pamet v GPU

### ISSUE THREAD

**Issue by michalblaha** [pavelzbornik/whisperX-FastAPI#5]
a nasledujici task skonci na Out of Memor
![Screenshot  2023-12-09 at 23 53 12](https://github.com/pavelzbornik/whisperX-FastAPI/assets/367276/39060876-cf88-4834-97be-3f8bd30efc29)

**Comment by pavelzbornik** [comment]
Ok, I wanted to save response time to load the model at the beginning at the API start, but I should clean the GPU memory. Surprised that it crashed on 4900 it should have plenty memory to hold all 3 models or I do something wrong :).

**Comment by michalblaha** [comment]
4090: there were more GPU processed (different application). You code allocates around 5GB GPU RAM for voice2text and sometime up to 10 GB GPU RAM for diarization (I didn't find any  rules for it yet)
